Update int_all_graph_resources.sql
dbt-labs/dbt-project-evaluator pull request #303
Opened 2023-02-06 15:57 UTC by DVDylanRoe

This is a:
- [x ] bug fix PR with no breaking changes
- [ ] new functionality

## Link to Issue 
Closes #302 

## Description & motivation
Before the script was identifying a model's type by finding the latest position a model type's folder name appears in the model's directory path. Now the folder name has been concatenated with a '/' before meaning the search is for a key directory not the just the key word.

## Integration Test Screenshot

## Checklist
- [ ] I have verified that these changes work locally on the following warehouses (Note: it's okay if you do not have access to all warehouses, this helps us understand what has been covered)
    - [ ] BigQuery
    - [ ] Postgres
    - [ ] Redshift
    - [ ] Snowflake
    - [ ] Databricks
    - [ ] DuckDB
- [ ] I have updated the README.md (if applicable)
- [ ] I have added tests & descriptions to my models (and macros if applicable)

2023-02-06 17:18 UTC, b-per requested changes
Thanks for the PR!

I just left a couple of comments before we can get it merged.

2023-02-06 17:18 UTC, b-per commented on models/marts/core/int_all_graph_resources.sql
> +            when {{ dbt.position("concat('/',naming_convention_folders.folder_name_value,'/')",'unioned_with_calc.directory_path') }} = 0 then null
`concat()` doesn't work with more than 2 arguments on Redshift, hence why the failing CI check. 
You could most likely use [`dbt.concat`](https://docs.getdbt.com/reference/dbt-jinja-functions/cross-database-macros#concat) instead.

2023-02-06 17:18 UTC, b-per commented on models/marts/core/int_all_graph_resources.sql
> +            when {{ dbt.position("concat('/',naming_convention_folders.folder_name_value,'/')",'unioned_with_calc.directory_path') }} = 0 then null
We also need to make it work for Windows users who have their files delimited with `\`.
There is [already a macro](https://github.com/dbt-labs/dbt-project-evaluator/blob/8a4c7e484a9ba81733c293d72ffeb447536a772a/macros/get_directory_pattern.sql#L2-L10) that you should be able to use that provides the file delimiter based on the OS being used.

2023-02-07 11:08 UTC, DVDylanRoe commented
@b-per replaced concat with dbt.concat and introduced get_directory_pattern() as requested. Has some issues as get_directory_pattern() wasn't returning the delimiter as a string once the code was compiled so the only work around I found is using "'" + get_directory_pattern() + "'".

2023-03-13 11:47 UTC, b-per commented
Thanks @DVDylanRoe and sorry for the delay. We are going to release a new version of the repo soon and we will take this change in account.

2023-03-13 11:56 UTC, b-per commented
Moving it to #317

2023-03-13 11:56 UTC, closed without merging