Log own custom rules
dbt-labs/dbt-project-evaluator pull request #408
Opened 2023-12-21 01:50 UTC by sadahry

This is a:
- [ ] bug fix PR with no breaking changes
- [ ] new functionality

## Link to Issue 

https://github.com/dbt-labs/dbt-project-evaluator/issues/407

## Description & motivation

Enable also to log error of our own rules by `print_dbt_project_evaluator_issues`

## Integration Test Screenshot

./run_test.sh snowflake

<img width="924" alt="スクリーンショット 2023-12-21 10 45 47" src="https://github.com/dbt-labs/dbt-project-evaluator/assets/28292300/1c69f3ac-ca49-43a7-ad8a-8109b1b200d4">

## Checklist
- [ ] I have verified that these changes work locally on the following warehouses (Note: it's okay if you do not have access to all warehouses, this helps us understand what has been covered)
    - [ ] BigQuery
    - [ ] Postgres
    - [ ] Redshift
    - [ ] Snowflake
    - [ ] Databricks
    - [ ] DuckDB
    - [ ] Trino/Starburst
- [ ] I have updated the README.md (if applicable)
- [ ] I have added tests & descriptions to my models (and macros if applicable)

## Usecase 

My custom rules is like that.

`{{ dbt project dir }}/models/dbt_project_evaluator/fct_public_models_without_exposures.sql`
```sql
with
    public_models as (
        select *
        from {{ ref("dbt_project_evaluator", "int_all_graph_resources") }}
        where resource_type = 'model' and is_public and not is_excluded
    ),
    models_with_exposure as (
        select resource_id
        from {{ ref("dbt_project_evaluator", "base_exposure_relationships") }}
    ),
    final as (
        select resource_name as model_name, is_public, false as has_exposure
        from public_models m
        where
            not exists (
                select 1 from models_with_exposure e where m.resource_id = e.resource_id
            )
    )

select *
from final {{ dbt_project_evaluator.filter_exceptions(model.name) }}
```

`{{ dbt project dir }}/models/dbt_project_evaluator/governance.yml`
```yaml
models:
  - name: fct_public_models_without_exposures
    description: This table shows each public model that does not have an exposure
    tests:
      - dbt_project_evaluator.is_empty:
          config:
            severity: "{{ env_var('DBT_PROJECT_EVALUATOR_SEVERITY', 'error') }}"
            store_failures_as: ephemeral
```

### Log example

logged like that (using fqn because package test alias show uuid like `dbt_project_evaluator_is_empty_xxxx`)

```
### List of issues raised by dbt_project_evaluator ###

-- dbt_project_evaluator.marts.governance.is_empty_fct_public_models_without_contract_ --
| RESOURCE_NAME                      | IS_PUBLIC | IS_CONTRACT_ENFORCED |
| ---------------------------------- | --------- | -------------------- |
| workspace_sandbox_dbt_sample_model |      True |                False |

-- my_dbt_package.dbt_project_evaluator.dbt_project_evaluator_is_empty_fct_public_models_without_exposures_ --
| MODEL_NAME                         | IS_PUBLIC | HAS_EXPOSURE |
| ---------------------------------- | --------- | ------------ |
| workspace_sandbox_dbt_sample_model |      True |        False |

-- dbt_project_evaluator.marts.governance.is_empty_fct_undocumented_public_models_ --
| RESOURCE_NAME                      | ACCESS | IS_DESCRIBED | TOTAL_DEFINED_COLUMNS | TOTAL_DESCRIBED_COLUMNS |
| ---------------------------------- | ------ | ------------ | --------------------- | ----------------------- |
| workspace_sandbox_dbt_sample_model | public |         True |                     1 |                       0 |
```

2024-01-22 15:25 UTC, dave-connors-3 commented
@sadahry this looks good! do you mind adding a quick bit of documentation [here](https://github.com/dbt-labs/dbt-project-evaluator/blob/main/docs/customization/issues-in-log.md) to describe that if you add a custom model and use the `dbt_project_evaluator.is_empty` test, you can see your own custom rules in the log output?

2024-01-23 14:05 UTC, sadahry commented
@dave-connors-3 Thank you for your review!

Of course, I'll explain and let you know once it's done.

2024-01-23 14:36 UTC, sadahry commented
@dave-connors-3 described it. Kindly confirm it!

2024-01-24 01:17 UTC, sadahry commented
It looks like a CI error occurred when I ran the trino test more than once

https://app.circleci.com/pipelines/github/dbt-labs/dbt-project-evaluator/813/workflows/00bbeeee-94aa-4551-b186-8320fc74d443/jobs/3738/steps
```
14:38:43    Database Error in model dim_model_7 (models/marts/intermediate/dim_model_7.sql)
  TrinoUserError(type=USER_ERROR, name=TABLE_ALREADY_EXISTS, message="line 6:5: Destination table '*************.dbt_project_evaluator_integration_tests_trino.dim_model_7__dbt_tmp' already exists", query_id=20240123_143830_81812_gp3ip)
```

2024-01-24 15:13 UTC, b-per commented
I re-ran the test and it was just a transient one on Trino.

The one failing on Databricks is known due to some `pandas` dependencies failiing in the latest `dbt-databricks`

2024-01-27 12:31 UTC, sadahry commented
All checks have passed (by someone's retry)
Thank you!

2024-02-01 16:56 UTC, graciegoheen requested changes

2024-02-01 16:56 UTC, graciegoheen commented on docs/customization/issues-in-log.md
> +
```suggestion

```

2024-02-01 16:56 UTC, graciegoheen commented on docs/customization/issues-in-log.md
> +      - dbt_project_evaluator.is_empty
```suggestion
models:
  - name: my_custom_rule_model
    description: This is my custom project evaluator check 
    tests:
      - dbt_project_evaluator.is_empty
```

2024-02-01 16:56 UTC, graciegoheen commented on docs/customization/issues-in-log.md
> +```
```suggestion

```

2024-02-01 16:56 UTC, graciegoheen commented on docs/customization/issues-in-log.md
> +`dbt_project_evaluator.`).
```suggestion

```

2024-02-01 16:57 UTC, graciegoheen approved these changes
Let's ship it! Thanks for all the work here!

2024-02-01 17:26 UTC, merged